spring.application.name=bpa-project
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.thymeleaf.cache=false
spring.config.import=optional:application-secret.properties

server.port=8080

app.storage.upload-dir=./storage/uploads
app.storage.analysis-dir=./storage/analysis
app.storage.report-dir=./storage/reports
